version: "2.4"

services:
  mongo:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      host:
  flask:
    build: ./backend
    env_file: ./backend/.env
    networks:
      - host
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  data:

networks:
  host: